// Auto-generated by generateAudio.js
export const audioMap = {
  "Welcome to Numbers Up To Ten Million! Let's start the journey.": "/assets/audio/audio_0.mp3",
  "A stadium holds 68,000 fans. A country has 9,450,000 people. Which number is bigger — and by how much? Let's learn how to read, compare, and master numbers this big!": "/assets/audio/audio_1.mp3",
  "Get ready to explore massive numbers! Let's master reading, writing, and comparing millions!": "/assets/audio/audio_2.mp3",
  "John visits a huge sports stadium. He says, 'This stadium seats 82,500 people. That's eighty-two thousand, five hundred!'": "/assets/audio/audio_3.mp3",
  "Sarah looks at a map of her city. 'My city has 1,240,000 people — one million, two hundred forty thousand!'": "/assets/audio/audio_4.mp3",
  "Every digit has its own place value: ten millions, millions, hundred thousands, ten thousands, thousands, hundreds, tens, and ones.": "/assets/audio/audio_5.mp3",
  "Mike visits an international airport. 'This airport welcomes 9,700,000 travellers every year!'": "/assets/audio/audio_6.mp3",
  "Priya compares two places. '1,240,000 is less than 9,700,000 — nine million, seven hundred thousand is much bigger!'": "/assets/audio/audio_7.mp3",
  "Ancient Symbol Decoder": "/assets/audio/audio_8.mp3",
  "Place Value Palace": "/assets/audio/audio_9.mp3",
  "Number Line Navigator": "/assets/audio/audio_10.mp3",
  "Expand and Compare Lab": "/assets/audio/audio_11.mp3",
  "Correct": "/assets/audio/audio_12.mp3",
  "Wrong": "/assets/audio/audio_13.mp3",
  "Let's play and test our knowledge!": "/assets/audio/audio_14.mp3",
  "We did it! We explored huge numbers. We learned how to read, build, plot, and compare them. Millions and ten millions are used to measure the biggest things in our world. Great job mastering these massive numbers!": "/assets/audio/audio_15.mp3"
};
